### ISSUE TITLE
New Option for Bye Teams

### ISSUE THREAD

**Issue by szarkowicz** [dambrisco/swiss-pairing#9]
Is this repo still being maintained? If so I would like to add a new option and have it integrated into the library.

The new option would be how to float the bye teams. Right now Bye teams are currently floated to the bottom - I would like to be able to float the bye teams to the top so the winning teams are rewarded with a bye instead of the losing teams.

I found the section in the code that needs to be changed, I can add the option and the check for it.

Please let me know if this is something you are interested in adding and I can make a proper pull request. If not I ll just modify my local version. 

Thanks

**Comment by dambrisco** [comment]
It's been a few years so apologies for the necro:

Under the Dutch system and in keeping with FIDE regulations, the lowest ranked player who has not already received a bye should be given the bye. However, this library is already a mild deviation in that it effectively enforces an all-play-all format, so additional deviations aren't out of the question.

I have no objection to this change were a PR to be submitted. I'd just add that I'd want to see a test that validated both directions over multiple rounds as part of that PR.

I'm going to close this issue for now assuming that this is no longer relevant, but please re-open if you'd like!
